# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/y/self-host/Alyzbane/Alamat-Inventory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/y/self-host/Alyzbane/Alamat-Inventory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/y/self-host/Alyzbane/Alamat-Inventory/CMakeFiles /cygdrive/y/self-host/Alyzbane/Alamat-Inventory//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/y/self-host/Alyzbane/Alamat-Inventory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named alamat

# Build rule for target.
alamat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alamat
.PHONY : alamat

# fast build rule for target.
alamat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/build
.PHONY : alamat/fast

alamat.o: alamat.cpp.o
.PHONY : alamat.o

# target to build an object file
alamat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/alamat.cpp.o
.PHONY : alamat.cpp.o

alamat.i: alamat.cpp.i
.PHONY : alamat.i

# target to preprocess a source file
alamat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/alamat.cpp.i
.PHONY : alamat.cpp.i

alamat.s: alamat.cpp.s
.PHONY : alamat.s

# target to generate assembly for a file
alamat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/alamat.cpp.s
.PHONY : alamat.cpp.s

archive.o: archive.cpp.o
.PHONY : archive.o

# target to build an object file
archive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/archive.cpp.o
.PHONY : archive.cpp.o

archive.i: archive.cpp.i
.PHONY : archive.i

# target to preprocess a source file
archive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/archive.cpp.i
.PHONY : archive.cpp.i

archive.s: archive.cpp.s
.PHONY : archive.s

# target to generate assembly for a file
archive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/archive.cpp.s
.PHONY : archive.cpp.s

entry.o: entry.cpp.o
.PHONY : entry.o

# target to build an object file
entry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/entry.cpp.o
.PHONY : entry.cpp.o

entry.i: entry.cpp.i
.PHONY : entry.i

# target to preprocess a source file
entry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/entry.cpp.i
.PHONY : entry.cpp.i

entry.s: entry.cpp.s
.PHONY : entry.s

# target to generate assembly for a file
entry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/entry.cpp.s
.PHONY : entry.cpp.s

login.o: login.cpp.o
.PHONY : login.o

# target to build an object file
login.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/login.cpp.o
.PHONY : login.cpp.o

login.i: login.cpp.i
.PHONY : login.i

# target to preprocess a source file
login.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/login.cpp.i
.PHONY : login.cpp.i

login.s: login.cpp.s
.PHONY : login.s

# target to generate assembly for a file
login.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/login.cpp.s
.PHONY : login.cpp.s

menu.o: menu.cpp.o
.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i
.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s
.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/menu.cpp.s
.PHONY : menu.cpp.s

prompt.o: prompt.cpp.o
.PHONY : prompt.o

# target to build an object file
prompt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/prompt.cpp.o
.PHONY : prompt.cpp.o

prompt.i: prompt.cpp.i
.PHONY : prompt.i

# target to preprocess a source file
prompt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/prompt.cpp.i
.PHONY : prompt.cpp.i

prompt.s: prompt.cpp.s
.PHONY : prompt.s

# target to generate assembly for a file
prompt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/prompt.cpp.s
.PHONY : prompt.cpp.s

screen.o: screen.cpp.o
.PHONY : screen.o

# target to build an object file
screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/screen.cpp.o
.PHONY : screen.cpp.o

screen.i: screen.cpp.i
.PHONY : screen.i

# target to preprocess a source file
screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/screen.cpp.i
.PHONY : screen.cpp.i

screen.s: screen.cpp.s
.PHONY : screen.s

# target to generate assembly for a file
screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/screen.cpp.s
.PHONY : screen.cpp.s

user.o: user.cpp.o
.PHONY : user.o

# target to build an object file
user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/user.cpp.o
.PHONY : user.cpp.o

user.i: user.cpp.i
.PHONY : user.i

# target to preprocess a source file
user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/user.cpp.i
.PHONY : user.cpp.i

user.s: user.cpp.s
.PHONY : user.s

# target to generate assembly for a file
user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alamat.dir/build.make CMakeFiles/alamat.dir/user.cpp.s
.PHONY : user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alamat"
	@echo "... alamat.o"
	@echo "... alamat.i"
	@echo "... alamat.s"
	@echo "... archive.o"
	@echo "... archive.i"
	@echo "... archive.s"
	@echo "... entry.o"
	@echo "... entry.i"
	@echo "... entry.s"
	@echo "... login.o"
	@echo "... login.i"
	@echo "... login.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... prompt.o"
	@echo "... prompt.i"
	@echo "... prompt.s"
	@echo "... screen.o"
	@echo "... screen.i"
	@echo "... screen.s"
	@echo "... user.o"
	@echo "... user.i"
	@echo "... user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

